apiVersion: v1
kind: Service
metadata:
  name: {{ include "dify.fullname" . }}-api
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    component: api
spec:
  ports:
    - port: 5001
      targetPort: 5001
      protocol: TCP
      name: http
  selector:
    {{- include "dify.selectorLabels" . | nindent 4 }}
    component: api
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dify.fullname" . }}-web
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    component: web
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "dify.selectorLabels" . | nindent 4 }}
    component: web
  type: ClusterIP
