apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "paymenter.fullname" . }}
  labels:
    {{- include "paymenter.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      services:
        - name: {{ include "paymenter.fullname" . }}
          port: 80
  tls:
    secretName: {{ include "paymenter.fullname" . }}-tls
    certResolver: {{ .Values.ingress.certResolver }}
