apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "wordpress.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "wordpress.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "wordpress.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: WORDPRESS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "wordpress.fullname" . }}
                  key: wordpress-username
            - name: WORDPRESS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "wordpress.fullname" . }}
                  key: wordpress-password
            - name: WORDPRESS_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ include "wordpress.fullname" . }}
                  key: wordpress-email
            - name: WORDPRESS_FIRST_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "wordpress.fullname" . }}
                  key: wordpress-first-name
            - name: WORDPRESS_LAST_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "wordpress.fullname" . }}
                  key: wordpress-last-name
            - name: WORDPRESS_BLOG_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "wordpress.fullname" . }}
                  key: wordpress-blog-name
            - name: MARIADB_HOST
              value: {{ .Values.externalDatabase.host }}
            - name: MARIADB_PORT_NUMBER
              value: "3306"
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "wordpress.fullname" . }}
                  key: mysql-root-password
            - name: MARIADB_DATABASE
              value: {{ .Values.externalDatabase.database }}
            - name: WORDPRESS_TABLE_PREFIX
              value: "wp_"
            - name: WORDPRESS_BLOG_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "wordpress.fullname" . }}
                  key: wordpress-blog-name
            - name: WORDPRESS_SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "wordpress.fullname" . }}
                  key: smtp-host
            - name: WORDPRESS_SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "wordpress.fullname" . }}
                  key: smtp-port
            - name: WORDPRESS_SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "wordpress.fullname" . }}
                  key: smtp-user
            - name: WORDPRESS_SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "wordpress.fullname" . }}
                  key: smtp-password
            - name: WORDPRESS_SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "wordpress.fullname" . }}
                  key: smtp-username
            - name: WORDPRESS_SMTP_PROTOCOL
              valueFrom:
                secretKeyRef:
                  name: {{ include "wordpress.fullname" . }}
                  key: smtp-protocol
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /wp-login.php
              port: http
            {{- if .Values.livenessProbe.enabled }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            {{- else }}
            initialDelaySeconds: 120
            periodSeconds: 10
            {{- end }}
          readinessProbe:
            httpGet:
              path: /wp-login.php
              port: http
            {{- if .Values.readinessProbe.enabled }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            {{- else }}
            initialDelaySeconds: 30
            periodSeconds: 5
            {{- end }}
          volumeMounts:
            - name: wordpress-data
              mountPath: /bitnami/wordpress
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: {{ include "wordpress.fullname" . }}-wordpress
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wordpress.fullname" . }}-wordpress
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}